import type { Tourist, Alert } from './types';

export const initialTourists: Tourist[] = [
  {
    id: 'T001',
    name: 'Aarav Sharma',
    age: 28,
    gender: 'Male',
    nationality: 'Indian',
    status: 'Active',
    location: { name: 'Kaziranga National Park', lat: 26.6, lng: 93.35 },
    itinerary: [
      { day: 1, location: 'Guwahati', activity: 'Hotel Check-in' },
      { day: 2, location: 'Kaziranga', activity: 'Jeep Safari' },
      { day: 3, location: 'Shillong', activity: 'Explore local markets' },
    ],
    emergencyContacts: [{ name: 'Priya Sharma', relation: 'Spouse', phone: '+919876543210' }],
    medicalFlags: ['Pollen Allergy'],
    blockchainVerified: true,
    profilePicture: 'https://i.pravatar.cc/150?u=aarav',
    riskLevel: 'Low',
  },
  {
    id: 'T002',
    name: 'Emily Watson',
    age: 34,
    gender: 'Female',
    nationality: 'British',
    status: 'Active',
    location: { name: 'Tawang Monastery', lat: 27.58, lng: 91.86 },
    itinerary: [
      { day: 1, location: 'Tezpur', activity: 'Arrival' },
      { day: 2, location: 'Dirang', activity: 'Sightseeing' },
      { day: 3, location: 'Tawang', activity: 'Visit Monastery' },
    ],
    emergencyContacts: [{ name: 'David Watson', relation: 'Father', phone: '+442079460958' }],
    medicalFlags: [],
    blockchainVerified: true,
    profilePicture: 'https://i.pravatar.cc/150?u=emily',
    riskLevel: 'Medium',
  },
  {
    id: 'T003',
    name: 'Rohan Joshi',
    age: 45,
    gender: 'Male',
    nationality: 'Indian',
    status: 'In-Distress',
    location: { name: 'Shillong Peak', lat: 25.54, lng: 91.87 },
    itinerary: [
      { day: 1, location: 'Shillong', activity: 'Umiam Lake' },
      { day: 2, location: 'Cherrapunji', activity: 'Nohkalikai Falls' },
      { day: 3, location: 'Shillong', activity: 'Shillong Peak' },
    ],
    emergencyContacts: [{ name: 'Anjali Joshi', relation: 'Spouse', phone: '+919988776655' }],
    medicalFlags: ['Hypertension'],
    blockchainVerified: false,
    profilePicture: 'https://i.pravatar.cc/150?u=rohan',
    riskLevel: 'High',
  },
  {
    id: 'T004',
    name: 'Chloe Dubois',
    age: 22,
    gender: 'Female',
    nationality: 'French',
    status: 'Active',
    location: { name: 'Majuli Island', lat: 27.02, lng: 94.22 },
    itinerary: [
      { day: 1, location: 'Jorhat', activity: 'Arrival' },
      { day: 2, location: 'Majuli', activity: 'Explore Satras' },
      { day: 3, location: 'Jorhat', activity: 'Departure' },
    ],
    emergencyContacts: [{ name: 'Luc Dubois', relation: 'Brother', phone: '+33123456789' }],
    medicalFlags: [],
    blockchainVerified: true,
    profilePicture: 'https://i.pravatar.cc/150?u=chloe',
    riskLevel: 'Low',
  },
  {
    id: 'T005',
    name: 'Vikram Singh',
    age: 31,
    gender: 'Male',
    nationality: 'Indian',
    status: 'Missing',
    location: { name: 'Dzukou Valley', lat: 25.68, lng: 94.02 },
    itinerary: [
      { day: 1, location: 'Kohima', activity: 'War Cemetery' },
      { day: 2, location: 'Dzukou Valley', activity: 'Trekking' },
      { day: 3, location: 'Kohima', activity: 'Return' },
    ],
    emergencyContacts: [{ name: 'Sunita Singh', relation: 'Mother', phone: '+919876543211' }],
    medicalFlags: [],
    blockchainVerified: true,
    profilePicture: 'https://i.pravatar.cc/150?u=vikram',
    riskLevel: 'High',
  },
  {
    id: 'T006',
    name: 'Kenji Tanaka',
    age: 41,
    gender: 'Male',
    nationality: 'Japanese',
    status: 'Active',
    location: { name: 'Loktak Lake', lat: 24.52, lng: 93.78 },
    itinerary: [
      { day: 1, location: 'Imphal', activity: 'Arrival' },
      { day: 2, location: 'Loktak Lake', activity: 'Boating' },
      { day: 3, location: 'Imphal', activity: 'Kangla Fort' },
    ],
    emergencyContacts: [{ name: 'Yuki Tanaka', relation: 'Spouse', phone: '+819012345678' }],
    medicalFlags: [],
    blockchainVerified: true,
    profilePicture: 'https://i.pravatar.cc/150?u=kenji',
    riskLevel: 'Medium',
  },
  {
    id: 'T007',
    name: 'Fatima Al-Sayed',
    age: 29,
    gender: 'Female',
    nationality: 'Emirati',
    status: 'Active',
    location: { name: 'Gangtok', lat: 27.33, lng: 88.61 },
    itinerary: [
      { day: 1, location: 'Bagdogra', activity: 'Arrival' },
      { day: 2, location: 'Gangtok', activity: 'MG Marg' },
      { day: 3, location: 'Tsomgo Lake', activity: 'Day Trip' },
    ],
    emergencyContacts: [{ name: 'Mohammed Al-Sayed', relation: 'Husband', phone: '+971501234567' }],
    medicalFlags: [],
    blockchainVerified: true,
    profilePicture: 'https://i.pravatar.cc/150?u=fatima',
    riskLevel: 'Low',
  },
  {
    id: 'T008',
    name: 'Isha Borah',
    age: 25,
    gender: 'Female',
    nationality: 'Indian',
    status: 'Active',
    location: { name: 'Ziro Valley', lat: 27.63, lng: 93.83 },
    itinerary: [
      { day: 1, location: 'Naharlagun', activity: 'Arrival' },
      { day: 2, location: 'Ziro', activity: 'Apatani Village Tour' },
      { day: 3, location: 'Ziro', activity: 'Trekking' },
    ],
    emergencyContacts: [{ name: 'Rajen Borah', relation: 'Father', phone: '+919864012345' }],
    medicalFlags: [],
    blockchainVerified: false,
    profilePicture: 'https://i.pravatar.cc/150?u=isha',
    riskLevel: 'Medium',
  },
  {
    id: 'T009',
    name: 'David Lee',
    age: 55,
    gender: 'Male',
    nationality: 'American',
    status: 'Active',
    location: { name: 'Kohima', lat: 25.66, lng: 94.10 },
    itinerary: [
        { day: 1, location: 'Dimapur', activity: 'Arrival' },
        { day: 2, location: 'Kohima', activity: 'Kisama Heritage Village' },
        { day: 3, location: 'Khonoma', activity: 'Green Village Tour' },
    ],
    emergencyContacts: [{ name: 'Susan Lee', relation: 'Spouse', phone: '+12125550184' }],
    medicalFlags: ['Diabetes Type 2'],
    blockchainVerified: true,
    profilePicture: 'https://i.pravatar.cc/150?u=david',
    riskLevel: 'High'
  },
  {
    id: 'T010',
    name: 'Aditi Rao',
    age: 32,
    gender: 'Female',
    nationality: 'Indian',
    status: 'Active',
    location: { name: 'Cherrapunji', lat: 25.27, lng: 91.73 },
    itinerary: [
        { day: 1, location: 'Shillong', activity: 'Arrival' },
        { day: 2, location: 'Cherrapunji', activity: 'Living Root Bridge' },
        { day: 3, location: 'Mawlynnong', activity: 'Cleanest Village Tour' },
    ],
    emergencyContacts: [{ name: 'Rahul Rao', relation: 'Brother', phone: '+919958991234' }],
    medicalFlags: [],
    blockchainVerified: true,
    profilePicture: 'https://i.pravatar.cc/150?u=aditi',
    riskLevel: 'Low'
  },
];

export const initialAlerts: Alert[] = [
    {
        id: 'A001',
        touristId: 'T003',
        type: 'SOS',
        tier: 'CRITICAL',
        message: 'SOS triggered near Shillong Peak.',
        timestamp: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      },
      {
        id: 'A002',
        touristId: 'T005',
        type: 'Missing',
        tier: 'CRITICAL',
        message: 'Vikram Singh reported missing during Dzukou Valley trek.',
        timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      },
      {
        id: 'A003',
        touristId: 'T002',
        type: 'Check-in Failure',
        tier: 'HIGH',
        message: 'Missed scheduled check-in at Tawang.',
        timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      },
      {
        id: 'A004',
        touristId: 'T001',
        type: 'Route Deviation',
        tier: 'MEDIUM',
        message: 'Significant deviation from Kaziranga itinerary.',
        timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      },
       {
        id: 'A005',
        touristId: 'T009',
        type: 'Check-in Failure',
        tier: 'HIGH',
        message: 'Missed medical check-in reminder.',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
];
